version: '3.8'

services:
  vllm-rerank:
    image: vllm-cpu:latest 
    container_name: vllm-rerank-cpu
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # 映射本地模型目录到容器
      - ./models/bge-reranker-v2-m3:/models/bge-reranker-v2-m3
      - ./reranker.py:/app/reranker.py
    
    command: [ "uvicorn","reranker:app","--host","0.0.0.0","--port","8000" ]
      
